### ISSUE TITLE
原理图bug

### ISSUE THREAD

**Issue by chengrongwp** [Ailikez/Various_MCU_Debugger_DIY#1]
首先感谢分享资料，我按照你的原理图自己画了一版，但是连上之后 VTarget再六点几V。是不是原理图还要改动一些？（参考制作资料中的那份原理图）

**Comment by chengrongwp** [comment]
是不是要按照你之前修改那样，不焊R13,R14,改R17为20K，并且短路四个焊盘？

**Comment by konosubakonoakua** [comment]
请问您是用的哪个版本的原理图呢？
jlinkv9mini_latest.pdf，这个才是最新版，之前那个bug是我看漏了之前的v93淘宝版本原理图，直接下拉了pc0导致vtarget一直是0Volt，现在原理图的修改会将pc0电压拉到1.66v，Vtarget应该是3.3v，这和之前的那个修改效果应该是一样的，你这个6.几Volt因该是上拉了pc0到3.3v所致
