### ISSUE TITLE
jlink连接小bug

### ISSUE THREAD

**Issue by HeXiaoShu520** [Ailikez/Various_MCU_Debugger_DIY#7]
请问一下博主，你有没有遇到这样的问题：jlink v9必须先连接目标板子再连接电脑才不会报错。但如果jlnik先连接电脑，再连目标板子，keil会提示jlink处于bootlaod模式，找不到固件，需要再下载固件（其实固件是有的）。

**Comment by konosubakonoakua** [comment]
没有过哎
